package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 24, 2009 10:02:44 AM by Hibernate Tools 3.2.1.GA



/**
 * ContestReservation generated by hbm2java
 */
public class ContestReservationBean  implements java.io.Serializable {


     private Integer id;
     private int contestId;
     private String userId;

    public ContestReservationBean() {
    }

    public ContestReservationBean(int contestId, String userId) {
       this.contestId = contestId;
       this.userId = userId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getContestId() {
        return this.contestId;
    }
    
    public void setContestId(int contestId) {
        this.contestId = contestId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }




}


