package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 28, 2009 1:32:08 PM by Hibernate Tools 3.2.1.GA



/**
 * Message generated by hbm2java
 */
public class MessageBean  implements java.io.Serializable {


     private Integer messageId;
     private String userId;
     private String question;
     private String response;
     private int status = 0;

    public MessageBean() {
    }

    public MessageBean(String userId, String question, String response) {
       this.userId = userId;
       this.question = question;
       this.response = response;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
}


