package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 5, 2009 10:46:26 PM by Hibernate Tools 3.2.1.GA



/**
 * SourceCode generated by hbm2java
 */
public class SourceCodeBean  implements java.io.Serializable {


    private int solutionId;
    private String source;

    public SourceCodeBean() {
    }

    public SourceCodeBean(int solutionId, String source) {
       this.solutionId = solutionId;
       this.source = source;
    }
   
    public int getSolutionId() {
        return this.solutionId;
    }
    
    public void setSolutionId(int solutionId) {
        this.solutionId = solutionId;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

}


