package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 4, 2009 10:16:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class UserBean  implements java.io.Serializable {


     private String userId = null;
     private String password = null;
     private String email = null;
     private String nick = null;
     private String school = null;
     private Integer submit = 0;
     private Integer solved = 0;
     private byte defunct = 0;
     private String ip = null;
     private Date accesstime = null;
     private int language = 0;
     private Date regTime = null;
     private int role = 0;

    public UserBean() {
    }

	
    public UserBean(String userId, String password) {
        this.userId = userId;
        this.password = password;
    }
    public UserBean(String userId, String password, String email, String nick,
            String school, String ip, Date accesstime, Date regTime, int role) {
       this.userId = userId;
       this.password = password;
       this.email = email;
       this.nick = nick;
       this.school = school;
       this.ip = ip;
       this.accesstime = accesstime;
       this.regTime = regTime;
       this.role = role;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public Integer getSubmit() {
        return this.submit;
    }
    
    public void setSubmit(Integer submit) {
        this.submit = submit;
    }
    public Integer getSolved() {
        return this.solved;
    }
    
    public void setSolved(Integer solved) {
        this.solved = solved;
    }
    public byte getDefunct() {
        return this.defunct;
    }
    
    public void setDefunct(byte defunct) {
        this.defunct = defunct;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getAccesstime() {
        return this.accesstime;
    }
    
    public void setAccesstime(Date accesstime) {
        this.accesstime = accesstime;
    }
    public int getLanguage() {
        return this.language;
    }
    
    public void setLanguage(int language) {
        this.language = language;
    }
    public Date getRegTime() {
        return this.regTime;
    }
    
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }




}


