package client;

public class LoginPanel extends javax.swing.JPanel {
    
    /** Creates new form LoginPanel */
    private javax.swing.JDialog dialog;
    public LoginPanel(javax.swing.JDialog d) {
        initComponents();
        dialog = d;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        JT_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JT_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JPF_Password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        JT_IP = new javax.swing.JTextField();
        JB_Public = new javax.swing.JButton();
        JB_Login = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 2));

        jLabel4.setText("Team||Person Name:");
        add(jLabel4);
        add(JT_Name);

        jLabel1.setText("Team||Person ID:");
        add(jLabel1);
        add(JT_ID);

        jLabel3.setText("Password:");
        add(jLabel3);

        JPF_Password.setEnabled(false);
        JPF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_PasswordActionPerformed(evt);
            }
        });
        add(JPF_Password);

        jLabel2.setText("ServerIP:");
        add(jLabel2);

        JT_IP.setText("222.204.222.2");
        add(JT_IP);

        JB_Public.setText("Public Set");
        JB_Public.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_PublicActionPerformed(evt);
            }
        });
        add(JB_Public);

        JB_Login.setText("Login");
        JB_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LoginActionPerformed(evt);
            }
        });
        add(JB_Login);
    }// </editor-fold>//GEN-END:initComponents

    private void JB_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LoginActionPerformed
        dialog.dispose();
        Control.login(JT_Name.getText(),JT_ID.getText(),JPF_Password.getText(),JT_IP.getText());
    }//GEN-LAST:event_JB_LoginActionPerformed

    private void JPF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_PasswordActionPerformed

    }//GEN-LAST:event_JPF_PasswordActionPerformed

    private void JB_PublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_PublicActionPerformed
        JT_ID.setText("12345678");
        //JPF_Password.setText("12345678");
        JT_Name.setText("12345678");
    }//GEN-LAST:event_JB_PublicActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Login;
    private javax.swing.JButton JB_Public;
    private javax.swing.JPasswordField JPF_Password;
    private javax.swing.JTextField JT_ID;
    private javax.swing.JTextField JT_IP;
    private javax.swing.JTextField JT_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    
}
