package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 4, 2009 10:16:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Contest generated by hbm2java
 */
public class ContestBean  implements java.io.Serializable {


     private int contestId;
     private String title;
     private Date startTime;
     private Date endTime;
     private byte defunct;
     private String description;
     private byte private_;

    public ContestBean() {
    }

	
    public ContestBean(int contestId, byte defunct, byte private_) {
        this.contestId = contestId;
        this.defunct = defunct;
        this.private_ = private_;
    }
    public ContestBean(int contestId, String title, Date startTime, Date endTime, byte defunct, String description, byte private_) {
       this.contestId = contestId;
       this.title = title;
       this.startTime = startTime;
       this.endTime = endTime;
       this.defunct = defunct;
       this.description = description;
       this.private_ = private_;
    }
   
    public int getContestId() {
        return this.contestId;
    }
    
    public void setContestId(int contestId) {
        this.contestId = contestId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public byte getDefunct() {
        return this.defunct;
    }
    
    public void setDefunct(byte defunct) {
        this.defunct = defunct;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getPrivate_() {
        return this.private_;
    }
    
    public void setPrivate_(byte private_) {
        this.private_ = private_;
    }




}


