package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 4, 2009 10:16:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Problem generated by hbm2java
 */
public class ProblemBean  implements java.io.Serializable {


     private int problemId;
     private String source;
     private String title;
     private String problemPath;
     private String inputPath;
     private String outputPath;
     private String stdcodePath;
     private Date createDate;
     private int timeLimit;
     private int caseTimeLimit;
     private int memoryLimit;
     private byte defunct;
     private Integer accepted;
     private Integer submit;
     private byte difficulty;
     private boolean special;
     private int category;

    public ProblemBean() {
    }
    
    public ProblemBean(int problemId, String source, String title, String problemPath, String inputPath, String outputPath, String stdcodePath, Date createDate, int timeLimit, int caseTimeLimit, int memoryLimit, byte defunct, Integer accepted, Integer submit, byte difficulty, boolean special, int category) {
       this.problemId = problemId;
       this.source = source;
       this.title = title;
       this.problemPath = problemPath;
       this.inputPath = inputPath;
       this.outputPath = outputPath;
       this.stdcodePath = stdcodePath;
       this.createDate = createDate;
       this.timeLimit = timeLimit;
       this.caseTimeLimit = caseTimeLimit;
       this.memoryLimit = memoryLimit;
       this.defunct = defunct;
       this.accepted = accepted;
       this.submit = submit;
       this.difficulty = difficulty;
       this.special = special;
       this.category = category;
    }
   
    public int getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(int problemId) {
        this.problemId = problemId;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getProblemPath() {
        return this.problemPath;
    }
    
    public void setProblemPath(String problemPath) {
        this.problemPath = problemPath;
    }
    public String getInputPath() {
        return this.inputPath;
    }
    
    public void setInputPath(String inputPath) {
        this.inputPath = inputPath;
    }
    public String getOutputPath() {
        return this.outputPath;
    }
    
    public void setOutputPath(String outputPath) {
        this.outputPath = outputPath;
    }
    public String getStdcodePath() {
        return this.stdcodePath;
    }
    
    public void setStdcodePath(String stdcodePath) {
        this.stdcodePath = stdcodePath;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public int getTimeLimit() {
        return this.timeLimit;
    }
    
    public void setTimeLimit(int timeLimit) {
        this.timeLimit = timeLimit;
    }
    public int getCaseTimeLimit() {
        return this.caseTimeLimit;
    }
    
    public void setCaseTimeLimit(int caseTimeLimit) {
        this.caseTimeLimit = caseTimeLimit;
    }
    public int getMemoryLimit() {
        return this.memoryLimit;
    }
    
    public void setMemoryLimit(int memoryLimit) {
        this.memoryLimit = memoryLimit;
    }
    public byte getDefunct() {
        return this.defunct;
    }
    
    public void setDefunct(byte defunct) {
        this.defunct = defunct;
    }
    public Integer getAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(Integer accepted) {
        this.accepted = accepted;
    }
    public Integer getSubmit() {
        return this.submit;
    }
    
    public void setSubmit(Integer submit) {
        this.submit = submit;
    }
    public byte getDifficulty() {
        return this.difficulty;
    }
    
    public void setDifficulty(byte difficulty) {
        this.difficulty = difficulty;
    }
    public boolean isSpecial() {
        return this.special;
    }
    
    public void setSpecial(boolean special) {
        this.special = special;
    }
    public int getCategory() {
        return this.category;
    }
    
    public void setCategory(int category) {
        this.category = category;
    }




}


