package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 4, 2009 10:16:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Solution generated by hbm2java
 */
public class SolutionBean  implements java.io.Serializable {

    private Integer solutionId;
    private int problemId;
    private String userId;
    private int runtime;
    private int memory;
    private Date submitDate;
    private short result;
    private byte language;
    private int contestId;
    private byte valid = 1;
    private short localJudgeResult = 0;
    private int percentage = 0;
    private SourceCodeBean sourceCode;
    private CompileinfoBean compileInfo;

    public SolutionBean() {
    }

	
    public SolutionBean(String userId, int contestId, int problemId, int runtime, int memory, Date submitDate, short result, byte language, short localResult) {
        this.problemId = problemId;
        this.userId = userId;
        this.runtime = runtime;
        this.memory = memory;
        this.submitDate = submitDate;
        this.result = result;
        this.language = language;
        this.contestId = contestId;
        this.localJudgeResult = localResult;
    }

    public SolutionBean(String userId, int contestId, int problemId, int runtime, int memory, Date submitDate, short result, byte language, short localResult, SourceCodeBean src) {
        this.problemId = problemId;
        this.userId = userId;
        this.runtime = runtime;
        this.memory = memory;
        this.submitDate = submitDate;
        this.result = result;
        this.language = language;
        this.contestId = contestId;
        this.localJudgeResult = localResult;
        this.sourceCode = src;
    }
   
    public Integer getSolutionId() {
        return this.solutionId;
    }
    
    public void setSolutionId(Integer solutionId) {
        this.solutionId = solutionId;
    }
    public int getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(int problemId) {
        this.problemId = problemId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public int getRuntime() {
        return this.runtime;
    }
    
    public void setRuntime(int runtime) {
        this.runtime = runtime;
    }
    public int getMemory() {
        return this.memory;
    }
    
    public void setMemory(int memory) {
        this.memory = memory;
    }
    public Date getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }
    public short getResult() {
        return this.result;
    }
    
    public void setResult(short result) {
        this.result = result;
    }
    public byte getLanguage() {
        return this.language;
    }
    
    public void setLanguage(byte language) {
        this.language = language;
    }
    public int getContestId() {
        return this.contestId;
    }
    
    public void setContestId(int contestId) {
        this.contestId = contestId;
    }
    
    public byte getValid() {
        return this.valid;
    }
    
    public void setValid(byte valid) {
        this.valid = valid;
    }

    public short getLocalJudgeResult() {
        return localJudgeResult;
    }

    public void setLocalJudgeResult(short localJudgeResult) {
        this.localJudgeResult = localJudgeResult;
    }

    public int getPercentage() {
        return percentage;
    }

    public void setPercentage(int percentage) {
        this.percentage = percentage;
    }

    public CompileinfoBean getCompileInfo() {
        return compileInfo;
    }

    public void setCompileInfo(CompileinfoBean compileInfo) {
        this.compileInfo = compileInfo;
    }

    public SourceCodeBean getSourceCode() {
        return sourceCode;
    }

    public void setSourceCode(SourceCodeBean sourceCode) {
        this.sourceCode = sourceCode;
    }

}


