
package client;

public class TestPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form TestPanel
     */
    public TestPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        JB_Run = new javax.swing.JButton();
        JB_Clear = new javax.swing.JButton();
        jPanelAll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_In = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_Out = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jToolBar.setFloatable(false);

        JB_Run.setText("Run");
        JB_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_RunActionPerformed(evt);
            }
        });
        jToolBar.add(JB_Run);

        JB_Clear.setText("Clear");
        JB_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ClearActionPerformed(evt);
            }
        });
        jToolBar.add(JB_Clear);

        add(jToolBar, java.awt.BorderLayout.NORTH);

        jPanelAll.setLayout(new java.awt.GridLayout(1, 2));

        JTA_In.setColumns(20);
        JTA_In.setRows(5);
        jScrollPane1.setViewportView(JTA_In);

        jPanelAll.add(jScrollPane1);

        JTA_Out.setColumns(20);
        JTA_Out.setRows(5);
        jScrollPane2.setViewportView(JTA_Out);

        jPanelAll.add(jScrollPane2);

        add(jPanelAll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void JB_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ClearActionPerformed
    JTA_In.setText("");
    JTA_Out.setText("");
}//GEN-LAST:event_JB_ClearActionPerformed

private void JB_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_RunActionPerformed
    if(Control.Run(JTA_In.getText())){
        JTA_Out.setText(Control.getTestOut());
    }
}//GEN-LAST:event_JB_RunActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Clear;
    private javax.swing.JButton JB_Run;
    private javax.swing.JTextArea JTA_In;
    private javax.swing.JTextArea JTA_Out;
    private javax.swing.JPanel jPanelAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
    
}
