package client.allpanel;

import client.Control;

public class LoginPanel extends javax.swing.JPanel {
    
    /** Creates new form LoginPanel */
    private javax.swing.JDialog dialog;
    public LoginPanel(javax.swing.JDialog d) {
        initComponents();
        dialog = d;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JT_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JPF_Password = new javax.swing.JPasswordField();
        JB_Public = new javax.swing.JButton();
        JB_Login = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("User Name:");
        add(jLabel1);
        add(JT_ID);

        jLabel3.setText("Password:");
        add(jLabel3);

        JPF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_PasswordActionPerformed(evt);
            }
        });
        add(JPF_Password);

        JB_Public.setText("Register");
        JB_Public.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_PublicActionPerformed(evt);
            }
        });
        add(JB_Public);

        JB_Login.setText("Login");
        JB_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LoginActionPerformed(evt);
            }
        });
        add(JB_Login);
    }// </editor-fold>//GEN-END:initComponents

    private void JB_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LoginActionPerformed
        //String name = JT_Name.getText();
        String username= JT_ID.getText();
        //if(!id.equals("")){
            dialog.dispose();
            //Control.login(JT_Name.getText(),JT_ID.getText(),JPF_Password.getText(),JT_IP.getText());
            Control.login(JT_ID.getText(),JPF_Password.getText());
        //}
    }//GEN-LAST:event_JB_LoginActionPerformed

    private void JPF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_PasswordActionPerformed
        JB_LoginActionPerformed(evt);
    }//GEN-LAST:event_JPF_PasswordActionPerformed

    private void JB_PublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_PublicActionPerformed
        dialog.dispose();
        javax.swing.JDialog d = new javax.swing.JDialog();
        RegisterPanel rp=new RegisterPanel(d);
        Control.getMainFrame().newDialog(d, rp, "Register");
    }//GEN-LAST:event_JB_PublicActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Login;
    private javax.swing.JButton JB_Public;
    private javax.swing.JPasswordField JPF_Password;
    private javax.swing.JTextField JT_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
}
