package cn.edu.dhu.acm.oj.judge;

import cn.edu.dhu.acm.oj.common.config.Const;

public class ManualJudgePanel extends javax.swing.JPanel {

    /** Creates new form HandJudgePanel */
    public ManualJudgePanel() {
        initComponents();
        for (int i = 0; i < Const.VERDICT.length; i++) {
            JCB_Result.addItem(Const.VERDICT[i]);
        }
        JCB_Result.setSelectedIndex(Const.QUEUE);
        JTA_CodeOut.setFont(Const.font);
        JTA_StandardOut.setFont(Const.font);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        JB_GetSubmit = new javax.swing.JButton();
        JB_LookInformation = new javax.swing.JButton();
        JB_LookPaper = new javax.swing.JButton();
        JB_Judge = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        JCB_Result = new javax.swing.JComboBox();
        JB_SendResult = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_StandardOut = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_CodeOut = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);

        JB_GetSubmit.setText("GetSubmit");
        JB_GetSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_GetSubmitActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_GetSubmit);

        JB_LookInformation.setText("LookInformation");
        JB_LookInformation.setEnabled(false);
        JB_LookInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LookInformationActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_LookInformation);

        JB_LookPaper.setText("LookPaper");
        JB_LookPaper.setEnabled(false);
        JB_LookPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LookPaperActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_LookPaper);

        JB_Judge.setText("Judge");
        JB_Judge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_JudgeActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_Judge);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jToolBar2.setFloatable(false);
        jToolBar2.add(JCB_Result);

        JB_SendResult.setText("SendResult");
        JB_SendResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SendResultActionPerformed(evt);
            }
        });
        jToolBar2.add(JB_SendResult);

        add(jToolBar2, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        JTA_StandardOut.setBackground(new java.awt.Color(0, 0, 0));
        JTA_StandardOut.setColumns(20);
        JTA_StandardOut.setForeground(new java.awt.Color(255, 255, 255));
        JTA_StandardOut.setRows(20);
        jScrollPane1.setViewportView(JTA_StandardOut);

        jSplitPane1.setLeftComponent(jScrollPane1);

        JTA_CodeOut.setBackground(new java.awt.Color(0, 0, 0));
        JTA_CodeOut.setColumns(20);
        JTA_CodeOut.setForeground(new java.awt.Color(255, 255, 255));
        JTA_CodeOut.setRows(20);
        jScrollPane2.setViewportView(JTA_CodeOut);

        jSplitPane1.setRightComponent(jScrollPane2);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void JB_LookInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LookInformationActionPerformed
        String str = "";
        str += "\nContestID : " + Control.getSolutionbean().getContestId();
        str += "\nProblemID : " + Control.getSolutionbean().getProblemId();
        str += "\nUserID : " + Control.getSolutionbean().getUserId();
        str += "\nLanguage : " + Const.LANGUAGE[Control.getSolutionbean().getLanguage()];
        str += "\nCode :\n" + Control.getSolutionbean().getSourceCode().getSource();
        new CodeInfFrame(str).setVisible(true);
    }//GEN-LAST:event_JB_LookInformationActionPerformed

    private void JB_LookPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LookPaperActionPerformed
        new ProblemLookFrame(Control.getPaperbean(), Control.getProblemID()).setVisible(true);
    }//GEN-LAST:event_JB_LookPaperActionPerformed

    private void JB_SendResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SendResultActionPerformed
        try {
            Control.getRunbean().setResult((short) JCB_Result.getSelectedIndex());
            Control.SendResult();
            JTA_StandardOut.setText("");
            JTA_CodeOut.setText("");
            JCB_Result.setSelectedIndex(Const.QUEUE);
            JB_LookPaper.setEnabled(false);
            JB_LookInformation.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_SendResultActionPerformed

    private void JB_JudgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_JudgeActionPerformed
        try {
            Control.Judge();
            JTA_StandardOut.setText(Control.getRunbean().getStdAns());
            JTA_CodeOut.setText(Control.getRunbean().getOutput());
            JCB_Result.setSelectedIndex(Control.getRunbean().getResult());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_JudgeActionPerformed

    private void JB_GetSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_GetSubmitActionPerformed
        try {
            Control.GetSubmit();
            JB_LookPaper.setEnabled(true);
            JB_LookInformation.setEnabled(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_GetSubmitActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_GetSubmit;
    private javax.swing.JButton JB_Judge;
    private javax.swing.JButton JB_LookInformation;
    private javax.swing.JButton JB_LookPaper;
    private javax.swing.JButton JB_SendResult;
    private javax.swing.JComboBox JCB_Result;
    private javax.swing.JTextArea JTA_CodeOut;
    private javax.swing.JTextArea JTA_StandardOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
