package cn.edu.dhu.acm.oj.judge;

/*
 * CodeInfFrame.java
 *
 * Created on 2007��5��26��, ����3:26
 */

/**
 *
 * @author  ��Ǻ�
 */
public class CodeInfFrame extends javax.swing.JFrame {
    
    /** Creates new form CodeInfFrame */
    public CodeInfFrame(String str) {
        initComponents();
        JTA_Information.setText(str);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" ��ɵĴ��� ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_Information = new javax.swing.JTextArea();

        setTitle("Information");
        JTA_Information.setBackground(new java.awt.Color(0, 0, 0));
        JTA_Information.setColumns(20);
        JTA_Information.setFont(new java.awt.Font("����", 1, 13));
        JTA_Information.setForeground(new java.awt.Color(255, 255, 255));
        JTA_Information.setRows(5);
        jScrollPane1.setViewportView(JTA_Information);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-508)/2, (screenSize.height-640)/2, 508, 640);
    }// </editor-fold>//GEN-END:initComponents

    // �������� - �������޸�//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_Information;
    private javax.swing.JScrollPane jScrollPane1;
    // ������������//GEN-END:variables
    
}
