package cn.edu.dhu.acm.oj.judge;

import cn.edu.dhu.acm.oj.judge.thread.*;

public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        Control.init(this);
        receiver = new Receiver();
        sender = new Sender();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        JB_Apply = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        JB_Auto = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        JT_Gotten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JT_Queue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACMjudge");

        JB_Apply.setText("Apply");
        JB_Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ApplyActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_Apply);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AutoJudge", "ManualJudge" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jComboBox1);

        JB_Auto.setText("Start");
        JB_Auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AutoActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_Auto);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jLabel1.setText("Have gotten :");
        jToolBar2.add(jLabel1);

        JT_Gotten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_GottenActionPerformed(evt);
            }
        });
        jToolBar2.add(JT_Gotten);

        jLabel2.setText("Now in queue :");
        jToolBar2.add(jLabel2);
        jToolBar2.add(JT_Queue);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.SOUTH);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void JT_GottenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_GottenActionPerformed
}//GEN-LAST:event_JT_GottenActionPerformed

    private void JB_ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ApplyActionPerformed
        AppFrame = new ApplyFrame(this);
        AppFrame.setVisible(true);

    }//GEN-LAST:event_JB_ApplyActionPerformed

    private void JB_AutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AutoActionPerformed
        if (JB_Auto.getText().equals("Start")) {
            if (thread == null) {
                thread = new Thread(r);
            }
            thread.start();
            JB_Auto.setText("Stop");
        } else {
            JB_Auto.setText("Start");
            try {
                thread.stop();
                thread = null;
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_JB_AutoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().toString().equals("ManualJudge")) {
            HJPanel = new ManualJudgePanel();
            getContentPane().add(HJPanel, java.awt.BorderLayout.CENTER);
            if (JB_Auto.getText().equals("Stop")) {
                try {
                    thread.stop();
                    thread = null;
                    JB_Auto.setText("Start");
                } catch (Exception ex) {
                }
            }
            JB_Auto.setEnabled(false);
            pack();
        } else {
            getContentPane().remove(HJPanel);
            HJPanel = null;
            JB_Auto.setEnabled(true);
            pack();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public void StartApply() {
        TReceiver = new Thread(receiver);
        TSender = new Thread(sender);
        TReceiver.start();
        TSender.start();
    }

    public void setQueue(int size) {
        JT_Queue.setText("" + size);
    }

    public void setGotten() {
        gotten++;
        JT_Gotten.setText("" + gotten);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Apply;
    private javax.swing.JButton JB_Auto;
    private javax.swing.JTextField JT_Gotten;
    private javax.swing.JTextField JT_Queue;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
    private ManualJudgePanel HJPanel;
    private RunAuto r = new RunAuto();
    private Thread thread = new Thread(r);
    private ApplyFrame AppFrame;
    private Thread TReceiver;
    private Thread TSender;
    private Receiver receiver;
    private Sender sender;
    private int gotten = 0;
}
