package cn.edu.dhu.acm.oj.client.panel;


public class MessagePanel extends javax.swing.JPanel {

    /** Creates new form MessagePanel */
    public MessagePanel(javax.swing.JDialog d,String str) {
        dialog = d;
        initComponents();
        TA_Message.setText(str);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JB_OK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TA_Message = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        JB_OK.setText("OK");
        JB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_OKActionPerformed(evt);
            }
        });
        jPanel1.add(JB_OK);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText(" ");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        TA_Message.setBackground(new java.awt.Color(238, 238, 238));
        TA_Message.setEditable(false);
        TA_Message.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel2.add(TA_Message, java.awt.BorderLayout.CENTER);

        jLabel2.setText("          ");
        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_END);

        jLabel3.setText("          ");
        jPanel2.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jLabel4.setText(" ");
        jPanel2.add(jLabel4, java.awt.BorderLayout.SOUTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void JB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_OKActionPerformed
        dialog.dispose();
    }//GEN-LAST:event_JB_OKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_OK;
    private javax.swing.JTextArea TA_Message;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JDialog dialog;
}
