package cn.edu.dhu.acm.oj.client.panel;

import cn.edu.dhu.acm.oj.common.paper.*;
import cn.edu.dhu.acm.oj.common.config.Const;
import cn.edu.dhu.acm.oj.client.Control;
import cn.edu.dhu.acm.oj.client.thread.*;

public class SubmitPanel extends javax.swing.JPanel {

    /** Creates new form SubmitPanel */
    public SubmitPanel(javax.swing.JDialog d) {
        initComponents();
        dialog = d;
        try {
            pb = Control.getPaperBean();
            int papernum = pb.getProblemCount();
            for (int i = 0; i < papernum; i++) {
                JCB_Problem.addItem((char) ('A' + i) + ".   " + pb.getProblemAt(i).getTitle());
            }
            JCB_Problem.setSelectedIndex(Control.getNowProblemNum());
            for (int i = 0; i < Const.LANGUAGE.length; i++) {
                JCB_Language.addItem(Const.LANGUAGE[i]);
            }
            JCB_Language.setSelectedItem(Control.getLanguage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        JCB_Language = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        JCB_Problem = new javax.swing.JComboBox();
        JB_Submit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jLabel3.setText("Language:");
        jToolBar1.add(jLabel3);

        JCB_Language.setToolTipText("Same as the language on codepanel");
        JCB_Language.setEnabled(false);
        jToolBar1.add(JCB_Language);

        jLabel2.setText("Problem:");
        jToolBar1.add(jLabel2);

        jToolBar1.add(JCB_Problem);

        JB_Submit.setText("Submit");
        JB_Submit.setFocusable(false);
        JB_Submit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_Submit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SubmitActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_Submit);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void JB_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SubmitActionPerformed
        dialog.dispose();
        long time = System.currentTimeMillis();
        if (time - Control.getLastSubmitTime() > Const.SUBMITSLEEP) {
            Control.setLastSubmitTime(time);
            try {
                RunSubmit runSubmit = new RunSubmit(JCB_Problem.getSelectedIndex(), JCB_Problem.getSelectedItem().toString());
                Thread thread = new Thread(runSubmit);
                thread.start();
            } catch (Exception e) {
            }
        } else {
            Control.getMainFrame().smallDialog("Can't Submit twice in " + Const.SUBMITSLEEP / 1000 + " sec.", "Error", 0);
        }
}//GEN-LAST:event_JB_SubmitActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Submit;
    private javax.swing.JComboBox JCB_Language;
    private javax.swing.JComboBox JCB_Problem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private PaperBean pb;
    javax.swing.JDialog dialog;
}
