package client;

import client.allpanel.*;

/**
 *
 * @author  Suncihai
 */
public class MainFrame extends MyFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        paperpanel = new PaperPanel();
        Control.setPaperpanel(paperpanel);
        initComponents();
        Control.setMainFrame(this);
        JP_Paper.add(paperpanel, java.awt.BorderLayout.CENTER);
        int i = Control.getAllcodecnt();
        String title = "Code00";
        codenum = 1;
        JTP_Code.add(title, new CodePanel(title, i, JTP_Code));
        JTP_Code.setTabComponentAt(i, new ButtonTabComponent(JTP_Code));
        Table.setModel(dtb = new javax.swing.table.DefaultTableModel(
                new Object[][]{ //{null, null, null, null, null, null, null}
                },
                new String[]{
                    "#", "ContestID", "ProblemID", "Verdict", "Language", "Run Time(ms)", "Submission Date"
                }) {

            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        Table.setEnabled(false);



        Control.setPaper("a+b.xml");
        paperpanel.setPaper();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TP_Main = new javax.swing.JTabbedPane();
        JP_Coding = new javax.swing.JPanel();
        JSP_PC = new javax.swing.JSplitPane();
        JP_Paper = new javax.swing.JPanel();
        JTP_Code = new javax.swing.JTabbedPane();
        JP_Status = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        JM_Tool = new javax.swing.JMenu();
        JMI_SetEnv = new javax.swing.JMenuItem();
        JMI_SetFile = new javax.swing.JMenuItem();
        JM_Help = new javax.swing.JMenu();
        JMI_Help = new javax.swing.JMenuItem();
        JMI_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JP_Coding.setLayout(new java.awt.BorderLayout());

        JSP_PC.setDividerLocation(382);
        JSP_PC.setDividerSize(7);
        JSP_PC.setOneTouchExpandable(true);

        JP_Paper.setLayout(new java.awt.BorderLayout());
        JSP_PC.setLeftComponent(JP_Paper);
        JSP_PC.setRightComponent(JTP_Code);

        JP_Coding.add(JSP_PC, java.awt.BorderLayout.CENTER);

        TP_Main.addTab("Coding", JP_Coding);

        JP_Status.setLayout(new java.awt.BorderLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        JP_Status.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        TP_Main.addTab("Status", JP_Status);

        getContentPane().add(TP_Main, java.awt.BorderLayout.CENTER);

        JM_Tool.setText("Tool");

        JMI_SetEnv.setText("SetCompilerPath");
        JMI_SetEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SetEnvActionPerformed(evt);
            }
        });
        JM_Tool.add(JMI_SetEnv);

        JMI_SetFile.setText("SetFilePath");
        JM_Tool.add(JMI_SetFile);

        MenuBar.add(JM_Tool);

        JM_Help.setText("Help");

        JMI_Help.setText("Help");
        JMI_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_HelpActionPerformed(evt);
            }
        });
        JM_Help.add(JMI_Help);

        JMI_About.setText("About");
        JM_Help.add(JMI_About);

        MenuBar.add(JM_Help);

        setJMenuBar(MenuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-783)/2, (screenSize.height-569)/2, 783, 569);
    }// </editor-fold>//GEN-END:initComponents

private void JMI_SetEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SetEnvActionPerformed
    javax.swing.JDialog dialog = new javax.swing.JDialog();
    EnvironmentPanel dlg = new EnvironmentPanel(dialog);
    newDialog(dialog, dlg, "SetEnvironment");
}//GEN-LAST:event_JMI_SetEnvActionPerformed

    private void JMI_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_HelpActionPerformed
    }//GEN-LAST:event_JMI_HelpActionPerformed

    public void NewCodePanel() {
        int i = Control.getAllcodecnt();
        String title = "Code";
        if (codenum < 10) {
            title += "0" + codenum;
        } else {
            title += codenum;
        }
        codenum++;
        JTP_Code.add(title, new CodePanel(title, i, JTP_Code));
        JTP_Code.setTabComponentAt(i, new ButtonTabComponent(JTP_Code));
    }

    public void OpenCodePanel() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser("./");
        if (chooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                String fileName = chooser.getSelectedFile().getPath();
                java.io.File file = new java.io.File(fileName);
                int fileSize = (int) file.length();
                int charReaded = 0;
                java.io.FileReader in = new java.io.FileReader(file);
                char[] data = new char[fileSize];
                while (in.ready()) {
                    charReaded += in.read(data, charReaded, fileSize - charReaded);
                }
                in.close();
                String SourceCode = "";
                for (int i = 0; i < charReaded; i++) {
                    SourceCode += data[i];
                }
                int i = Control.getAllcodecnt();
                String title = file.getName();
                if (title.indexOf(".") != -1) {
                    title = title.substring(0, title.indexOf("."));
                }
                CodePanel cp = new CodePanel(title, i, JTP_Code);
                cp.setCode(SourceCode);
                JTP_Code.add(title, cp);
                JTP_Code.setTabComponentAt(i, new ButtonTabComponent(JTP_Code));

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public void updateRow(Object[] row) {
        Integer qid = (Integer) row[0];
        int len = dtb.getRowCount();
        boolean find = false;
        int i;
        for (i = 0; i < len; i++) {
            Integer id = (Integer) dtb.getValueAt(i, 0);
            if (qid.equals(id)) {
                find = true;
                break;
            }
        }
        if (!find) {
            dtb.addRow(row);
        } else {
            dtb.setValueAt(row[1], i, 1);
            dtb.setValueAt(row[3], i, 3);
            dtb.setValueAt(row[5], i, 5);
            dtb.setValueAt(row[6], i, 6);
        }
        Table.repaint();
    }

    public void showStatus() {
        TP_Main.setSelectedIndex(1);
    }

    public void setPaper(){
        paperpanel.setPaper();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMI_About;
    private javax.swing.JMenuItem JMI_Help;
    private javax.swing.JMenuItem JMI_SetEnv;
    private javax.swing.JMenuItem JMI_SetFile;
    private javax.swing.JMenu JM_Help;
    private javax.swing.JMenu JM_Tool;
    private javax.swing.JPanel JP_Coding;
    private javax.swing.JPanel JP_Paper;
    private javax.swing.JPanel JP_Status;
    private javax.swing.JSplitPane JSP_PC;
    private javax.swing.JTabbedPane JTP_Code;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTabbedPane TP_Main;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private PaperPanel paperpanel;
    private static java.util.Timer t1;
    private static java.util.Timer t2;
    private int codenum;
    public javax.swing.table.DefaultTableModel dtb;
}
