/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubmissionFrame.java
 *
 * Created on 2009-5-9, 14:39:36
 */
package client;

import config.Const;

/**
 *
 * @author Administrator
 */
public class SubmissionFrame extends javax.swing.JFrame {

    /** Creates new form SubmissionFrame */
    public SubmissionFrame() {
        initComponents();
        Table.setModel(dtb = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    //{null, null, null, null, null, null, null}
                },
                new String[]{
                    "#", "ContestID", "ProblemID", "Verdict", "Language", "Run Time(ms)", "Submission Date"
                }) {

            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        Table.setEnabled(false);
    }

    public void updateRow(Object[] row) {
        Integer qid=(Integer)row[0];
        int len=dtb.getRowCount();
        boolean find=false;
        int i;
        for(i=0;i<len;i++){
            Integer id = (Integer)dtb.getValueAt(i, 0);
            if(qid.equals(id)){
                find=true;
                break;
            }
        }
        if(!find){
            dtb.addRow(row);
        }
        else{
            dtb.setValueAt(row[1], i, 1);
            dtb.setValueAt(row[3], i, 3);
            dtb.setValueAt(row[5], i, 5);
            dtb.setValueAt(row[6], i, 6);
        }
        Table.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setTitle("Submissions");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScrollPane.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable Table;
    // End of variables declaration//GEN-END:variables
    public javax.swing.table.DefaultTableModel dtb;
}
