package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 5, 2009 10:46:26 PM by Hibernate Tools 3.2.1.GA



/**
 * Compileinfo generated by hbm2java
 */
public class CompileinfoBean  implements java.io.Serializable {


     private int solutionId;
     private String error;

    public CompileinfoBean() {
    }

	
    public CompileinfoBean(int solutionId) {
        this.solutionId = solutionId;
    }
    public CompileinfoBean(int solutionId, String error) {
       this.solutionId = solutionId;
       this.error = error;
    }
   
    public int getSolutionId() {
        return this.solutionId;
    }
    
    public void setSolutionId(int solutionId) {
        this.solutionId = solutionId;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }




}


