package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 5, 2009 11:15:53 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Contest generated by hbm2java
 */
public class ContestBean  implements java.io.Serializable {


     private Integer contestId;
     private String title;
     private Date startTime;
     private Date endTime;
     private byte defunct;
     private String description;
     private byte private_;
     private int status;

    public ContestBean() {
    }

    public ContestBean(String title, Date startTime, Date endTime, 
            String description, byte private_, int status) {
       this.title = title;
       this.startTime = startTime;
       this.endTime = endTime;
       this.description = description;
       this.private_ = private_;
       this.status = status;
    }
   
    public Integer getContestId() {
        return this.contestId;
    }
    
    public void setContestId(Integer contestId) {
        this.contestId = contestId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public byte getDefunct() {
        return this.defunct;
    }
    
    public void setDefunct(byte defunct) {
        this.defunct = defunct;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getPrivate_() {
        return this.private_;
    }
    
    public void setPrivate_(byte private_) {
        this.private_ = private_;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


