package cn.edu.dhu.acm.oj.persistence.beans;
// Generated May 4, 2009 10:16:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Solution generated by hbm2java
 */
public class SolutionBean  implements java.io.Serializable {


     private Integer solutionId;
     private int problemId;
     private String userId;
     private int runtime;
     private int memory;
     private Date submitDate;
     private short result;
     private byte language;
     private int contestId;
     private byte valid;
     private String compileInfo;
     private String sourceCode;

    public SolutionBean() {
    }

	
    public SolutionBean(int problemId, String userId, int runtime, int memory, Date submitDate, short result, byte language, int contestId, byte valid) {
        this.problemId = problemId;
        this.userId = userId;
        this.runtime = runtime;
        this.memory = memory;
        this.submitDate = submitDate;
        this.result = result;
        this.language = language;
        this.contestId = contestId;
        this.valid = valid;
    }
    public SolutionBean(int problemId, String userId, int runtime, int memory, Date submitDate, short result, byte language, int contestId, byte valid, String compileInfo, String sourceCode) {
       this.problemId = problemId;
       this.userId = userId;
       this.runtime = runtime;
       this.memory = memory;
       this.submitDate = submitDate;
       this.result = result;
       this.language = language;
       this.contestId = contestId;
       this.valid = valid;
       this.compileInfo = compileInfo;
       this.sourceCode = sourceCode;
    }
   
    public Integer getSolutionId() {
        return this.solutionId;
    }
    
    public void setSolutionId(Integer solutionId) {
        this.solutionId = solutionId;
    }
    public int getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(int problemId) {
        this.problemId = problemId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public int getRuntime() {
        return this.runtime;
    }
    
    public void setRuntime(int runtime) {
        this.runtime = runtime;
    }
    public int getMemory() {
        return this.memory;
    }
    
    public void setMemory(int memory) {
        this.memory = memory;
    }
    public Date getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }
    public short getResult() {
        return this.result;
    }
    
    public void setResult(short result) {
        this.result = result;
    }
    public byte getLanguage() {
        return this.language;
    }
    
    public void setLanguage(byte language) {
        this.language = language;
    }
    public int getContestId() {
        return this.contestId;
    }
    
    public void setContestId(int contestId) {
        this.contestId = contestId;
    }
    public byte getValid() {
        return this.valid;
    }
    
    public void setValid(byte valid) {
        this.valid = valid;
    }
    public String getCompileInfo() {
        return this.compileInfo;
    }
    
    public void setCompileInfo(String compileInfo) {
        this.compileInfo = compileInfo;
    }
    public String getSourceCode() {
        return this.sourceCode;
    }
    
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }




}


