package cn.edu.dhu.acm.oj.client;

import cn.edu.dhu.acm.oj.client.panel.*;
import cn.edu.dhu.acm.oj.common.config.Const;

public class MainFrame extends MyFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        paperpanel = new PaperPanel();
        Control.setPaperpanel(paperpanel);
        initComponents();
        Control.setMainFrame(this);
        JP_Paper.add(paperpanel, java.awt.BorderLayout.CENTER);
        int i = Control.getAllcodecnt();
        String title = "New0";
        codenum = 1;
        JTP_Code.add(title, new CodePanel(title, i, JTP_Code));
        JTP_Code.setTabComponentAt(i, new ButtonTabComponent(JTP_Code));

        Table.setModel(dtb = new javax.swing.table.DefaultTableModel(
                new Object[][]{}, Const.TABLECOLNAME) {

            Class[] types = Const.TABLECOLTYPE;

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        Table.setEnabled(false);
        Control.setPaper(Const.INITPAPER);
        paperpanel.setPaper();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TP_Main = new javax.swing.JTabbedPane();
        JP_Coding = new javax.swing.JPanel();
        JSP_PC = new javax.swing.JSplitPane();
        JP_Paper = new javax.swing.JPanel();
        JTP_Code = new javax.swing.JTabbedPane();
        JP_Status = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        JP_Rank = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JEP_Rank = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        JB_Reflash = new javax.swing.JButton();
        TF_URL = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        JM_Tool1 = new javax.swing.JMenu();
        JMI_New = new javax.swing.JMenuItem();
        JMI_Open = new javax.swing.JMenuItem();
        JMI_Save = new javax.swing.JMenuItem();
        JMI_SaveAs = new javax.swing.JMenuItem();
        JMI_Logout = new javax.swing.JMenuItem();
        JMI_Exit = new javax.swing.JMenuItem();
        JM_Tool = new javax.swing.JMenu();
        JMI_SetEnv = new javax.swing.JMenuItem();
        JMI_SetFile = new javax.swing.JMenuItem();
        JM_Help = new javax.swing.JMenu();
        JMI_Help = new javax.swing.JMenuItem();
        JMI_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JP_Coding.setLayout(new java.awt.BorderLayout());

        JSP_PC.setDividerLocation(382);
        JSP_PC.setDividerSize(7);
        JSP_PC.setOneTouchExpandable(true);

        JP_Paper.setLayout(new java.awt.BorderLayout());
        JSP_PC.setLeftComponent(JP_Paper);
        JSP_PC.setRightComponent(JTP_Code);

        JP_Coding.add(JSP_PC, java.awt.BorderLayout.CENTER);

        TP_Main.addTab("Coding", JP_Coding);

        JP_Status.setLayout(new java.awt.BorderLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        JP_Status.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        TP_Main.addTab("Status", JP_Status);

        JP_Rank.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(JEP_Rank);

        JP_Rank.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        JB_Reflash.setText("Reflash");
        JB_Reflash.setFocusable(false);
        JB_Reflash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_Reflash.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_Reflash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ReflashActionPerformed(evt);
            }
        });
        jToolBar1.add(JB_Reflash);

        TF_URL.setEditable(false);
        TF_URL.setText("http://acm.dhu.edu.cn/dhuoj/contestrank?cid=3");
        TF_URL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_URLActionPerformed(evt);
            }
        });
        jToolBar1.add(TF_URL);

        JP_Rank.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        TP_Main.addTab("Rank", JP_Rank);

        getContentPane().add(TP_Main, java.awt.BorderLayout.CENTER);

        JM_Tool1.setText("File");

        JMI_New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        JMI_New.setText("New");
        JMI_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_NewActionPerformed(evt);
            }
        });
        JM_Tool1.add(JMI_New);

        JMI_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        JMI_Open.setText("Open");
        JMI_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_OpenActionPerformed(evt);
            }
        });
        JM_Tool1.add(JMI_Open);

        JMI_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMI_Save.setText("Save");
        JMI_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SaveActionPerformed(evt);
            }
        });
        JM_Tool1.add(JMI_Save);

        JMI_SaveAs.setText("Save As");
        JMI_SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SaveAsActionPerformed(evt);
            }
        });
        JM_Tool1.add(JMI_SaveAs);

        JMI_Logout.setText("Logout");
        JM_Tool1.add(JMI_Logout);

        JMI_Exit.setText("Exit");
        JM_Tool1.add(JMI_Exit);

        MenuBar.add(JM_Tool1);

        JM_Tool.setText("Tool");

        JMI_SetEnv.setText("SetCompilerPath");
        JMI_SetEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SetEnvActionPerformed(evt);
            }
        });
        JM_Tool.add(JMI_SetEnv);

        JMI_SetFile.setText("SetFilePath");
        JM_Tool.add(JMI_SetFile);

        MenuBar.add(JM_Tool);

        JM_Help.setText("Help");

        JMI_Help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        JMI_Help.setText("Help");
        JMI_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_HelpActionPerformed(evt);
            }
        });
        JM_Help.add(JMI_Help);

        JMI_About.setText("About");
        JM_Help.add(JMI_About);

        MenuBar.add(JM_Help);

        setJMenuBar(MenuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-808)/2, (screenSize.height-571)/2, 808, 571);
    }// </editor-fold>//GEN-END:initComponents

private void JMI_SetEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SetEnvActionPerformed
    javax.swing.JDialog dialog = new javax.swing.JDialog();
    EnvironmentPanel dlg = new EnvironmentPanel(dialog);
    newDialog(dialog, dlg, "SetEnvironment");
}//GEN-LAST:event_JMI_SetEnvActionPerformed

    private void JMI_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_HelpActionPerformed
    }//GEN-LAST:event_JMI_HelpActionPerformed

    private void JMI_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_NewActionPerformed
        NewCodePanel();
}//GEN-LAST:event_JMI_NewActionPerformed

    private void JMI_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_OpenActionPerformed
        OpenCodePanel();
    }//GEN-LAST:event_JMI_OpenActionPerformed

    private void JMI_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SaveActionPerformed
        CodePanel cp = (CodePanel) JTP_Code.getSelectedComponent();
        if (cp != null) {
            try {
                cp.Save();
            } catch (Exception e) {
                smallDialog("Save File Error!", "Error", 0);
            }
        }
    }//GEN-LAST:event_JMI_SaveActionPerformed

    private void JMI_SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SaveAsActionPerformed
        CodePanel cp = (CodePanel) JTP_Code.getSelectedComponent();
        if (cp != null) {
            try {
            } catch (Exception e) {
                smallDialog("Save File Error!", "Error", 0);
            }
        }

    }//GEN-LAST:event_JMI_SaveAsActionPerformed

    private void JB_ReflashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ReflashActionPerformed
        try {
            JEP_Rank.setPage(TF_URL.getText());
        } catch (Exception e) {
            JEP_Rank.setText(e.toString());
        }
}//GEN-LAST:event_JB_ReflashActionPerformed

    private void TF_URLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_URLActionPerformed
        this.JB_ReflashActionPerformed(evt);
}//GEN-LAST:event_TF_URLActionPerformed

    public void NewCodePanel() {
        int i = Control.getAllcodecnt();
        String title = "New";
        title += codenum;
        codenum++;
        JTP_Code.add(title, new CodePanel(title, i, JTP_Code));
        JTP_Code.setTabComponentAt(i, new ButtonTabComponent(JTP_Code));
        JTP_Code.setSelectedIndex(i);
    }

    public void OpenCodePanel() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser("./");
        if (chooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                String fileName = chooser.getSelectedFile().getPath();
                java.io.File file = new java.io.File(fileName);
                int fileSize = (int) file.length();

                int charReaded = 0;
                java.io.FileReader in = new java.io.FileReader(file);
                char[] data = new char[fileSize];
                while (in.ready()) {
                    charReaded += in.read(data, charReaded, fileSize - charReaded);
                }
                in.close();
                StringBuffer SourceCode = new StringBuffer();
                for (int i = 0; i < charReaded; i++) {
                    SourceCode.append(data[i]);
                }

                int i = Control.getAllcodecnt();
                String title = file.getName();
                CodePanel cp = new CodePanel(title, i, JTP_Code);
                cp.setCode(SourceCode.toString());
                JTP_Code.add(title, cp);
                JTP_Code.setTabComponentAt(i, new ButtonTabComponent(JTP_Code));
                JTP_Code.setSelectedIndex(i);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public void deleteqid(Integer qid) {
        int len = dtb.getRowCount();
        for (int i = 0; i < len; i++) {
            Integer id = (Integer) dtb.getValueAt(i, 0);
            if (qid.equals(id)) {
                dtb.removeRow(i);
                break;
            }
        }
        Table.repaint();
    }

    public String getRowString(Integer qid) {
        String ans = "";
        int len = dtb.getRowCount();
        for (int i = 0; i < len; i++) {
            Integer id = (Integer) dtb.getValueAt(i, 0);
            if (qid.equals(id)) {
                for (int j = 2; j < Const.TABLECOLNAME.length - 1; j++) {
                    ans += String.format("%s : %s\n", Const.TABLECOLNAME[j], dtb.getValueAt(i, j));
                }
                break;
            }
        }
        return ans;
    }

    public void updateRow(Object[] row) {
        Integer qid = (Integer) row[0];
        int len = dtb.getRowCount();
        boolean find = false;
        int i;
        for (i = 0; i < len; i++) {
            Integer id = (Integer) dtb.getValueAt(i, 0);
            if (qid.equals(id)) {
                find = true;
                break;
            }
        }
        if (!find) {
            dtb.addRow(row);
        } else {
            dtb.setValueAt(row[1], i, 1);
            dtb.setValueAt(row[3], i, 3);
            dtb.setValueAt(row[5], i, 5);
            dtb.setValueAt(row[6], i, 6);
        }
        Table.repaint();
    }

    public void showStatus() {
        TP_Main.setSelectedIndex(1);
    }

    public void setPaper() {
        paperpanel.setPaper();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Reflash;
    private javax.swing.JEditorPane JEP_Rank;
    private javax.swing.JMenuItem JMI_About;
    private javax.swing.JMenuItem JMI_Exit;
    private javax.swing.JMenuItem JMI_Help;
    private javax.swing.JMenuItem JMI_Logout;
    private javax.swing.JMenuItem JMI_New;
    private javax.swing.JMenuItem JMI_Open;
    private javax.swing.JMenuItem JMI_Save;
    private javax.swing.JMenuItem JMI_SaveAs;
    private javax.swing.JMenuItem JMI_SetEnv;
    private javax.swing.JMenuItem JMI_SetFile;
    private javax.swing.JMenu JM_Help;
    private javax.swing.JMenu JM_Tool;
    private javax.swing.JMenu JM_Tool1;
    private javax.swing.JPanel JP_Coding;
    private javax.swing.JPanel JP_Paper;
    private javax.swing.JPanel JP_Rank;
    private javax.swing.JPanel JP_Status;
    private javax.swing.JSplitPane JSP_PC;
    private javax.swing.JTabbedPane JTP_Code;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField TF_URL;
    private javax.swing.JTabbedPane TP_Main;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private PaperPanel paperpanel;
    private int codenum;
    public javax.swing.table.DefaultTableModel dtb;
}
